version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Build wheel package
          command: ./setup.py bdist_wheel sdist
      - persist_to_workspace:
          root: .
          paths:
            - ./dist/*.whl
            - ./dist/*.tar.gz
  test-py38: &test-py38
    docker:
      - image: cimg/python:3.8
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unit tests
          command: |
            py=$(python3 --version | sed -r 's|.* 3\.([0-9]+)\..*|3.\1|')
            virtualenv -p python3 venv$py
            . venv$py/bin/activate
            pip3 install $(ls ./dist/*.whl)[test,all]
            python3 -m reconplogger_tests coverage xml coverage_py$py.xml
      - persist_to_workspace:
          root: .
          paths:
            - ./coverage_*.xml
  test-py312:
    <<: *test-py38
    docker:
      - image: cimg/python:3.12
  test-py311:
    <<: *test-py38
    docker:
      - image: cimg/python:3.11
  test-py310:
    <<: *test-py38
    docker:
      - image: cimg/python:3.10
  test-py39:
    <<: *test-py38
    docker:
      - image: cimg/python:3.9
  codecov:
    docker:
      - image: curlimages/curl:latest
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Code coverage
          command: |
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            for py in 3.8 3.9 3.10 3.11 3.12; do
              ./codecov \
                --nonZero \
                --token $CODECOV_TOKEN_RECONPLOGGER \
                --flags py$py \
                --file coverage_py$py.xml
            done
  publish-pypi:
    docker:
      - image: cimg/python:3.10
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Publish Release on PyPI
          command: |
            pip3 install -U twine
            twine upload --username __token__ --password "${PYPI_TOKEN}" ./dist/*.whl ./dist/*.tar.gz

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build: &buildreq
          filters: &tagfilter
            tags:
              only: /^v\d+\.\d+\.\d+.*$/
      - test-py38: &testreq
          <<: *buildreq
          requires:
            - build
      - test-py312:
          <<: *testreq
      - test-py311:
          <<: *testreq
      - test-py310:
          <<: *testreq
      - test-py39:
          <<: *testreq
      - codecov:
          <<: *testreq
          requires:
            - test-py312
            - test-py311
            - test-py310
            - test-py39
            - test-py38
      - publish-pypi:
          filters:
            branches:
              ignore: /.*/
            <<: *tagfilter
          context: pypi-upload-context
          requires:
            - codecov
